title: TUM CSD
description: > # this means to ignore newlines until "baseurl:"
  TUM CSD event 2019
baseurl: "" # the subpath of your site, e.g. /blog
url: "Your-Link.github.io" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

facebook:
  app_id:

social:
  name: TUM ASTA
  link: "https://www.facebook.com/"

google_site_verification: googleXXXXXXXXXXXXXXXX.html

include: ['_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com
  - title: twitter
    url: https://twitter.com

# Build settings
markdown: kramdown
permalink: pretty

defaults:
  - scope:
      path: "_assets/images"
    values:
      image: true